### ISSUE TITLE
"Request Result" should be "Response Payload" in API docs

### ISSUE THREAD

**Issue by petemoore** [taskcluster/taskcluster-docs#40]
Our API docs use the headings:

* Request Payload
* Request Result

This should instead be:

* Request Payload
* Response Payload

Justification: the sections outline the payload of the http request and http response respectively.

**Comment by jonasfj** [comment]
go ahead... I don't care.. :)

**Comment by jonasfj** [comment]
it's just terminology... but yeah, Payload is better...

**Comment by petemoore** [comment]
thanks! i'll give it a spin.

**Comment by petemoore** [comment]
Done!
